### ISSUE TITLE
Tokenization error on Symfony Expression Language Condition

### ISSUE THREAD

**Issue by TheJotob** [martin-helmich/typo3-typoscript-parser#47]
I get an Linting Error "Tokenization error: Cannot tokenize line "[56 in tree.rootLineIds]"" when I try to use the symfony expression "[56 in tree.rootLineIds]" as condition.

**Comment by martin-helmich** [comment]
Support for Symfony expressions was originally introduced in #39. Turns out there's already a test case for (almost) this exact piece of code, which passes successfully:

https://github.com/martin-helmich/typo3-typoscript-parser/blob/eedd34773442722e114b9072afcb585110c5e8bf/tests/unit/Tokenizer/TokenizerTest.php#L175-L183

Could you check which version of the `helmich/typo3-typoscript-parser` -- ⚠️ **Caution**, not the same package as `helmich/typo3-typoscript-lint` -- you are using?

**Comment by martin-helmich** [comment]
Closed due to lack of feedback. Feel free to re-open if this issue is still relevant for you.
